### ISSUE TITLE
SongBrowser

### ISSUE THREAD

**Issue by astroluxx** [Spooky323/ImageCoverExpander#1]
when clicking any song in song browser it breaks the menu and you need to restart the game

**Comment by Spooky323** [comment]
Me and Pixel are aware of the issue and are working to get it fixed asap

**Comment by Spooky323** [comment]
You mean more songs downloader? If so me and Pixel are awake of the issue and working asap to fix it

**Comment by Spooky323** [comment]
fixed in the new version
